FROM python:3

ENV PYTHONUNBUFFERED 1
WORKDIR /app/api
ADD requirements.txt /app/api
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ADD . /app/
ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]